name: Ruby Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      ollama:
        image: ollama/ollama
        ports:
          - "11434:11434"
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: false  # Отключаем автоматический bundle install
    
    - name: Fix platform mismatch
      run: |
        bundle lock --add-platform x86_64-linux
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        bundle install
    
    - name: Run Test
      run: |
        bundle exec ruby -I test test/ollama_client_test.rb