name: Ruby Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      ollama:
        image: ollama/ollama
        ports:
          - "11434:11434"
    
    steps:
    - uses: actions/checkout@v4
    
        
    - name: Run tests
      run: -I test test/ollama_client_test.rb